FROM golang:1.23

ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i 's#http://deb.debian.org#http://mirrors.tuna.tsinghua.edu.cn#g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update && apt install imagemagick -y

WORKDIR /opt
RUN git clone https://github.com/hzyitc/AmlImg.git
WORKDIR /opt/AmlImg

RUN cp buildAllPlatforms.sh build.sh && \
    sed -i 's/# platforms=($(go tool dist list))/platforms=(linux\/amd64)/g' build.sh && \
    bash build.sh && \
    mv ./bin/AmlImg_* /bin/AmlImg && \
    chmod +x /bin/AmlImg

COPY scripts/packer/pack-resource-image scripts/packer/pack-burn-image scripts/packer/pack-image /bin/
RUN chmod +x /bin/pack-*
WORKDIR /uboot
CMD ["pack-image"]